/* Auto-generated by CMake – do not edit manually */
#pragma once

/* Library version */
#define LIBICM20948_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define LIBICM20948_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define LIBICM20948_VERSION_PATCH @PROJECT_VERSION_PATCH@

/* libgpiod version – defined when libgpiod >= 2.0 is available */
#cmakedefine HAVE_LIBGPIOD_V2 @HAVE_LIBGPIOD_V2@

/* Enable DMP firmware support (set by -DICM20948_USE_DMP=ON) */
#cmakedefine ICM20948_USE_DMP
